name       : libarchive
version    : 3.4.1
release    : 27
source     :
    - https://github.com/libarchive/libarchive/archive/v3.4.1.tar.gz : 772e8b066d84d2f15c89a6cfcba482878eb1270f56aa1d484710e904d84cc4c1
homepage   : http://www.libarchive.org/
license    : BSD-2-Clause
component  :
    - programming.library
    - bin : system.devel
summary    : Library for reading and writing streaming archives
description: |
    The libarchive library provides a flexible interface for reading and writing archives in various formats such as tar and cpio.
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(liblz4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libzstd)
    - pkgconfig(nettle)
    - acl-devel
    - attr-devel
    - bzip2-devel
patterns   :
    - bin :
        - /usr/bin
        - /usr/share/man/man1
        - /usr/share/man/man5
    - devel :
        - /usr/share/man/man3
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
