name       : libarchive
version    : 3.6.1
release    : 37
source     :
    - https://github.com/libarchive/libarchive/releases/download/v3.6.1/libarchive-3.6.1.tar.xz : 5a411aceb978f43e626f0c2d1812ddd8807b645ed892453acabd532376c148e6
homepage   : http://www.libarchive.org/
license    : BSD-2-Clause
component  :
    - programming.library
    - bin : system.devel
summary    : Library for reading and writing streaming archives
description: |
    The libarchive library provides a flexible interface for reading and writing archives in various formats such as tar and cpio.
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(liblz4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libzstd)
    - pkgconfig(nettle)
    - acl-devel
    - attr-devel
    - bzip2-devel
patterns   :
    - bin :
        - /usr/bin
        - /usr/share/man/man1
        - /usr/share/man/man5
    - devel :
        - /usr/share/man/man3
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
