name       : libarchive
version    : 3.3.1
release    : 15
source     :
    - https://github.com/libarchive/libarchive/archive/v3.3.1.tar.gz : ff138120fe7fca1bd02bed6f06d6869c7497658904a2f8916947f9a3f3257377
homepage   : http://www.libarchive.org/
license    : BSD-2-Clause
component  : programming.library
summary    : Library for reading and writing streaming archives
description: |
    The libarchive library provides a flexible interface for reading and writing archives in various formats such as tar and cpio.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(nettle)
patterns   :
    - bin :
        - /usr/bin
        - /usr/share/man/man1
        - /usr/share/man/man5
    - devel :
        - /usr/share/man/man3
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
