name       : libarchive
version    : 3.3.0
release    : 14
source     :
    - https://github.com/libarchive/libarchive/archive/v3.3.0.tar.gz : 046045c5d52413579e7dadb2f8464b2ca3feadb9f68380bf535b4885cf32eaee
homepage   : http://www.libarchive.org/
license    : BSD-2-Clause
component  : programming.library
summary    : Library for reading and writing streaming archives
description: |
    The libarchive library provides a flexible interface for reading and writing archives in various formats such as tar and cpio.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(nettle)
patterns   :
    - bin :
        - /usr/bin
        - /usr/share/man/man1
        - /usr/share/man/man5
    - devel :
        - /usr/share/man/man3
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
