name        : libarchive
version     : 3.1.2
release     : 9
source      :
    - http://www.libarchive.org/downloads/libarchive-3.1.2.tar.gz : eb87eacd8fe49e8d90c8fdc189813023ccc319c5e752b01fb6ad0cc7b2c53d5e
homepage    : http://www.libarchive.org/
license     :
    - BSD-2-Clause
summary     : Library for reading and writing streaming archives
builddeps   :
    - pkgconfig(libxml-2.0)
    - pkgconfig(nettle)
description : |
    The libarchive library provides a flexible interface for reading and writing archives in
    various formats such as tar and cpio.
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2013-0211.patch
    %patch -p1 < $pkgfiles/security/cve-2015-2304.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
