name       : libarchive
version    : 3.2.1
release    : 12
source     :
    - http://www.libarchive.org/downloads/libarchive-3.2.1.tar.gz : 72ee1a4e3fd534525f13a0ba1aa7b05b203d186e0c6072a8a4738649d0b3cfd2
homepage   : http://www.libarchive.org/
license    :
    - BSD-2-Clause
summary    : Library for reading and writing streaming archives
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(nettle)
patterns   :
    - bin :
        - /usr/bin
        - /usr/share/man/man1
        - /usr/share/man/man5
    - devel :
        - /usr/share/man/man3
description: |
    The libarchive library provides a flexible interface for reading and writing archives in
    various formats such as tar and cpio.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
