name       : libarchive
version    : 3.6.2
release    : 39
source     :
    - https://github.com/libarchive/libarchive/releases/download/v3.6.2/libarchive-3.6.2.tar.xz : 9e2c1b80d5fbe59b61308fdfab6c79b5021d7ff4ff2489fb12daf0a96a83551d
homepage   : http://www.libarchive.org/
license    : BSD-2-Clause
component  :
    - programming.library
    - bin : system.devel
summary    : Library for reading and writing streaming archives
description: |
    The libarchive library provides a flexible interface for reading and writing archives in various formats such as tar and cpio.
builddeps  :
    - pkgconfig(bzip2)
    - pkgconfig(ext2fs)
    - pkgconfig(libacl)
    - pkgconfig(libattr)
    - pkgconfig(liblz4)
    - pkgconfig(liblzma)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libzstd)
    - pkgconfig(nettle)
patterns   :
    - bin :
        - /usr/bin
        - /usr/share/man/man1
        - /usr/share/man/man5
    - devel :
        - /usr/share/man/man3
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install

    # remove iconv from libarchive.pc requirements.
    # Upstream issue: https://github.com/libarchive/libarchive/issues/1766
    sed -i "s/iconv //" $installdir/%libdir%/pkgconfig/libarchive.pc
