name       : libarchive
version    : 3.4.2
release    : 28
source     :
    - https://github.com/libarchive/libarchive/archive/v3.4.2.tar.gz : ce926cea1195b53ee0868020c00f8c98ecf15497856b79c85430749634827f80
homepage   : http://www.libarchive.org/
license    : BSD-2-Clause
component  :
    - programming.library
    - bin : system.devel
summary    : Library for reading and writing streaming archives
description: |
    The libarchive library provides a flexible interface for reading and writing archives in various formats such as tar and cpio.
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(liblz4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libzstd)
    - pkgconfig(nettle)
    - acl-devel
    - attr-devel
    - bzip2-devel
patterns   :
    - bin :
        - /usr/bin
        - /usr/share/man/man1
        - /usr/share/man/man5
    - devel :
        - /usr/share/man/man3
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
