name       : libarchive
version    : 3.5.3
release    : 36
source     :
    - https://github.com/libarchive/libarchive/releases/download/v3.5.3/libarchive-3.5.3.tar.xz : 5cac725dd4be31c4a10b65d30f29dc957ea29ef3d758df6e46e8ae90a996a19a
homepage   : http://www.libarchive.org/
license    : BSD-2-Clause
component  :
    - programming.library
    - bin : system.devel
summary    : Library for reading and writing streaming archives
description: |
    The libarchive library provides a flexible interface for reading and writing archives in various formats such as tar and cpio.
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(liblz4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libzstd)
    - pkgconfig(nettle)
    - acl-devel
    - attr-devel
    - bzip2-devel
patterns   :
    - bin :
        - /usr/bin
        - /usr/share/man/man1
        - /usr/share/man/man5
    - devel :
        - /usr/share/man/man3
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
