name       : libarchive
version    : 3.4.3
release    : 29
source     :
    - https://github.com/libarchive/libarchive/archive/v3.4.3.tar.gz : 19556c1c67aacdff547fd719729630444dbc7161c63eca661a310676a022bb01
homepage   : http://www.libarchive.org/
license    : BSD-2-Clause
component  :
    - programming.library
    - bin : system.devel
summary    : Library for reading and writing streaming archives
description: |
    The libarchive library provides a flexible interface for reading and writing archives in various formats such as tar and cpio.
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(liblz4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libzstd)
    - pkgconfig(nettle)
    - acl-devel
    - attr-devel
    - bzip2-devel
patterns   :
    - bin :
        - /usr/bin
        - /usr/share/man/man1
        - /usr/share/man/man5
    - devel :
        - /usr/share/man/man3
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
